### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ryanirilli** [gocardless/es6-angularjs#8]
Not sure how to deal with these errors just yet but here are the logs from npm install. Thanks for any help here!

node version v0.12.2
npm version 2.13.4

```
Ryans-MacBook-Pro:wallet-apps2 ryanirilli$ git clone git@github.com:gocardless/es6-angularjs.git
Cloning into 'es6-angularjs'...
remote: Counting objects: 2194, done.
remote: Total 2194 (delta 0), reused 0 (delta 0), pack-reused 2194
Receiving objects: 100% (2194/2194), 2.32 MiB | 1012.00 KiB/s, done.
Resolving deltas: 100% (758/758), done.
Checking connectivity... done.
Ryans-MacBook-Pro:wallet-apps2 ryanirilli$ cd es6-angularjs/
Ryans-MacBook-Pro:es6-angularjs ryanirilli$ npm install
npm WARN package.json es6-angular@0.0.1-pre No license field.
npm WARN engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.13.4"})
npm WARN engine karma@0.12.28: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.13.4"})
npm WARN peerDependencies The peer dependency karma@>=0.11.11 included from karma-sauce-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> websocket@1.0.14 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/fb-flo/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> canvas@1.1.2 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/assetgraph-sprite/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/assetgraph-sprite/node_modules/canvas
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> canvas@1.1.6 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/histogram/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/histogram/node_modules/canvas
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing canvas@1.1.2
npm WARN optional dep failed, continuing histogram@0.1.5

> fsevents@0.3.1 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> contextify@0.1.9 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:34:17: error: no member named 'ContextDisposedNotification' in 'v8::V8'
        v8::V8::ContextDisposedNotification();
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-uglify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> pngquant-bin@2.0.0 postinstall /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/express-processimage/node_modules/pngquant/node_modules/pngquant-bin
> node lib/install.js

-
  success : pngquant pre-build test passed successfully



> pngquant-bin@0.1.7 postinstall /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/pngquant/node_modules/pngquant-bin
> node index.js

✓ pre-build test passed successfully

> contextify@0.1.9 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/express-processimage/node_modules/svgfilter/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:34:17: error: no member named 'ContextDisposedNotification' in 'v8::V8'
        v8::V8::ContextDisposedNotification();
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/express-processimage/node_modules/svgfilter/node_modules/assetgraph/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

> ws@0.4.32 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm WARN optional dep failed, continuing svgfilter@0.4.0

> node-zopfli@1.1.4 install /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build --build-from-source

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/cache.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/deflate.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/gzip_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/hash.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/katajainen.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/lz77.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/squeeze.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/tree.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/util.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zlib_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zopfli_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/zopflipng_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng_util.o
  SOLINK_MODULE(target) Release/zopfli.node
  COPY /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/node_modules/assetgraph-builder/node_modules/node-zopfli/lib/binding/node-v14-darwin-x64/zopfli.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN engine xmlbuilder@2.4.5: wanted: {"node":"0.8.x || 0.10.x || 0.11.x"} (current: {"node":"0.12.2","npm":"2.13.4"})
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ryanirilli/projects/go/src/github.com/Points/wallet-apps2/es6-angularjs/npm-debug.log
Ryans-MacBook-Pro:es6-angularjs ryanirilli$
```

**Comment by jackfranklin** [comment]
Does it install on Node 0.10? I think we need to bump some versions so we're happy on Node 0.12.
